name: Build all platforms

on:
  workflow_dispatch:
    inputs:
      imgui_commit:
        description: 'SHA-1 hash to checkout'
        default: ''
        required: false
      fetch_depth:
        description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
        default: '1'
        required: true

jobs:
  call-build-linux:
    uses: ./.github/workflows/linux.yml
  # call-build-linux-cross:
  #   needs: call-build-linux
  #   uses: ./.github/workflows/linux_cross.yml
  # call-build-macos:
  #   needs: call-build-linux-cross
  #   uses: ./.github/workflows/macos.yml
  # call-build-windows:
  #   needs: call-build-macos
  #   uses: ./.github/workflows/windows.yml
